const HSK_THEME_LABEL_VI: Readonly<Record<string, string>> = {
  "pronunciation and tone foundations": "Phát âm và nền tảng thanh điệu",
  "greetings and identity": "Chào hỏi và giới thiệu bản thân",
  "numbers, dates and time": "Số, ngày tháng và thời gian",
  "family and people": "Gia đình và con người",
  "daily routine": "Sinh hoạt hằng ngày",
  "food and drinks": "Ăn uống",
  "shopping and prices": "Mua sắm và giá cả",
  "directions and transport": "Chỉ đường và giao thông",
  "school and basic work": "Trường học và công việc cơ bản",
  "health and simple needs": "Sức khỏe và nhu cầu cơ bản",
  "weather and hobbies": "Thời tiết và sở thích",
  "integrated survival conversations": "Hội thoại sinh tồn tổng hợp",

  "expanded routines and schedules": "Lịch trình và sinh hoạt mở rộng",
  "home and neighbourhood": "Nhà ở và khu phố",
  "health and appointments": "Sức khỏe và lịch hẹn",
  "study and classroom interaction": "Học tập và giao tiếp lớp học",
  "workplace basics": "Giao tiếp công sở cơ bản",
  "weather and seasonal plans": "Thời tiết và kế hoạch theo mùa",
  "preferences and hobbies": "Sở thích và lựa chọn cá nhân",
  "travel bookings": "Đặt vé và đặt chỗ du lịch",
  "services and transactions": "Dịch vụ và giao dịch",
  "describing past events": "Kể lại sự việc đã xảy ra",
  "simple plans and intentions": "Kế hoạch và dự định đơn giản",
  "problem solving": "Xử lý vấn đề",
  "social invitations": "Lời mời và giao tiếp xã hội",
  "integrated daily-life conversations": "Hội thoại đời sống tổng hợp",

  "connected narration": "Kể chuyện có liên kết",
  "comparison and choice": "So sánh và lựa chọn",
  "reasons and explanations": "Lý do và giải thích",
  "travel and accommodation": "Du lịch và lưu trú",
  "public services": "Dịch vụ công cộng",
  "study projects": "Dự án học tập",
  "work tasks": "Nhiệm vụ công việc",
  "health and wellbeing": "Sức khỏe và chất lượng sống",
  "relationships and social life": "Quan hệ và đời sống xã hội",
  "news and everyday media": "Tin tức và truyền thông đời thường",
  "technology in daily life": "Công nghệ trong đời sống",
  "culture and festivals": "Văn hóa và lễ hội",
  "handling misunderstandings": "Xử lý hiểu lầm",
  "planning and negotiation": "Lập kế hoạch và thương lượng",
  "longer role plays": "Hội thoại nhập vai dài hơn",
  "elementary-stage integration": "Tổng hợp bậc sơ cấp",

  "multi-turn social conversation": "Hội thoại xã hội nhiều lượt",
  "storytelling and sequencing": "Kể chuyện và sắp xếp trình tự",
  "cause and consequence": "Nguyên nhân và kết quả",
  "opinions and reasons": "Quan điểm và lập luận",
  "workplace collaboration": "Hợp tác nơi làm việc",
  "study and presentations": "Học tập và thuyết trình",
  "community and public life": "Cộng đồng và đời sống công cộng",
  "media and current affairs": "Truyền thông và thời sự",
  "travel problem solving": "Xử lý sự cố khi du lịch",
  "consumer decisions": "Quyết định mua sắm và tiêu dùng",
  "health information": "Thông tin sức khỏe",
  "environment and lifestyle": "Môi trường và lối sống",
  "technology and communication": "Công nghệ và giao tiếp",
  "culture and entertainment": "Văn hóa và giải trí",
  "formal versus informal register": "Phong cách trang trọng và thân mật",
  "structured listening summaries": "Nghe và tóm tắt có cấu trúc",
  "discussion strategies": "Chiến lược thảo luận",
  "intermediate-stage integration I": "Tổng hợp trung cấp I",

  "long-form listening": "Nghe nội dung dài",
  "interviews and announcements": "Phỏng vấn và thông báo",
  "organized opinions": "Trình bày quan điểm có tổ chức",
  "workplace decision making": "Ra quyết định trong công việc",
  "academic discussion": "Thảo luận học thuật",
  "social issues": "Các vấn đề xã hội",
  "economy and consumer life": "Kinh tế và đời sống tiêu dùng",
  "science and technology": "Khoa học và công nghệ",
  "health and public information": "Sức khỏe và thông tin công cộng",
  "culture, arts and media": "Văn hóa, nghệ thuật và truyền thông",
  "environment and sustainability": "Môi trường và phát triển bền vững",
  "travel and intercultural situations": "Du lịch và tình huống liên văn hóa",
  "persuasion and disagreement": "Thuyết phục và bất đồng",
  "summarizing information": "Tóm tắt thông tin",
  "presentation skills": "Kỹ năng thuyết trình",
  "register and politeness": "Phong cách ngôn ngữ và phép lịch sự",
  "figurative everyday language": "Ngôn ngữ hình tượng đời thường",
  "argument structure": "Cấu trúc lập luận",
  "extended role play": "Nhập vai mở rộng",
  "intermediate-stage integration II": "Tổng hợp trung cấp II",

  "extended argument": "Lập luận mở rộng",
  "implicit meaning": "Hàm ý và ý nghĩa ngầm",
  "stance and nuance": "Lập trường và sắc thái",
  "formal meetings": "Họp hành trang trọng",
  "professional problem solving": "Giải quyết vấn đề chuyên nghiệp",
  "academic lectures": "Bài giảng học thuật",
  "news analysis": "Phân tích tin tức",
  "public policy and society": "Chính sách công và xã hội",
  "business and economics": "Kinh doanh và kinh tế",
  "science and innovation": "Khoa học và đổi mới",
  "culture and history": "Văn hóa và lịch sử",
  "literature and storytelling": "Văn học và nghệ thuật kể chuyện",
  "environment": "Môi trường",
  "intercultural communication": "Giao tiếp liên văn hóa",
  "humour and pragmatic meaning": "Hài hước và nghĩa dụng học",
  "register shifting": "Chuyển đổi phong cách ngôn ngữ",
  "spontaneous discussion": "Thảo luận ứng biến",
  "debate foundations": "Nền tảng tranh biện",
  "synthesis from multiple speakers": "Tổng hợp thông tin từ nhiều người nói",
  "high-load listening": "Nghe nội dung mật độ cao",
  "intermediate-stage integration III": "Tổng hợp trung cấp III",

  "academic lectures and seminars": "Bài giảng và hội thảo học thuật",
  "professional briefings": "Báo cáo chuyên môn",
  "culture and society": "Văn hóa và xã hội",
  "policy and economics": "Chính sách và kinh tế",
  "long-form interviews": "Phỏng vấn chuyên sâu",
  "evidence and argument": "Bằng chứng và lập luận",
  "critical response": "Phản hồi phản biện",
  "formal presentation": "Thuyết trình trang trọng",
  "specialist vocabulary strategies": "Chiến lược từ vựng chuyên ngành",
  "cross-domain synthesis": "Tổng hợp liên lĩnh vực",
  "advanced register": "Phong cách ngôn ngữ cao cấp",
  "rhetorical structure": "Cấu trúc tu từ",
  "negotiation": "Đàm phán",
  "debate": "Tranh biện",
  "media analysis": "Phân tích truyền thông",
  "historical and cultural context": "Bối cảnh lịch sử và văn hóa",
  "research communication": "Giao tiếp nghiên cứu",
  "professional scenarios": "Tình huống chuyên nghiệp",
  "high-density listening": "Nghe nội dung có mật độ thông tin cao",
  "spontaneous extended speech": "Nói ứng biến kéo dài",
  "multiple-source synthesis": "Tổng hợp từ nhiều nguồn",
  "advanced pragmatics": "Dụng học nâng cao",
  "advanced-stage integration I": "Tổng hợp cao cấp I",

  "complex multi-sided argument": "Lập luận phức tạp nhiều chiều",
  "speaker stance and implication": "Lập trường người nói và hàm ý",
  "interdisciplinary topics": "Chủ đề liên ngành",
  "professional leadership communication": "Giao tiếp lãnh đạo chuyên nghiệp",
  "academic critique": "Phê bình học thuật",
  "advanced negotiation": "Đàm phán nâng cao",
  "formal public speaking": "Diễn thuyết công khai trang trọng",
  "specialist interviews": "Phỏng vấn chuyên ngành",
  "rhetorical nuance": "Sắc thái tu từ",
  "idiomatic and figurative speech": "Thành ngữ và ngôn ngữ hình tượng",
  "dense media content": "Nội dung truyền thông mật độ cao",
  "policy and institutional language": "Ngôn ngữ chính sách và thể chế",
  "science communication": "Truyền thông khoa học",
  "arts and criticism": "Nghệ thuật và phê bình",
  "ethics and society": "Đạo đức và xã hội",
  "cross-cultural mediation": "Trung gian giao tiếp liên văn hóa",
  "rapid turn taking": "Đối thoại luân phiên tốc độ cao",
  "subtle disagreement": "Bất đồng tinh tế",
  "register transformation": "Biến đổi phong cách diễn đạt",
  "multi-source synthesis": "Tổng hợp đa nguồn",
  "extended unscripted response": "Phản hồi dài không theo kịch bản",
  "technical explanation": "Giải thích kỹ thuật",
  "critical debate": "Tranh biện phản biện",
  "advanced listening under load": "Nghe nâng cao dưới tải thông tin lớn",
  "professional simulations": "Mô phỏng tình huống chuyên nghiệp",
  "advanced-stage integration II": "Tổng hợp cao cấp II",

  "specialized academic discourse": "Diễn ngôn học thuật chuyên sâu",
  "specialized professional discourse": "Diễn ngôn nghề nghiệp chuyên sâu",
  "abstract reasoning": "Lập luận trừu tượng",
  "precision and reformulation": "Độ chính xác và diễn đạt lại",
  "critical evaluation": "Đánh giá phản biện",
  "high-stakes presentation": "Thuyết trình trong tình huống quan trọng",
  "expert interview": "Phỏng vấn chuyên gia",
  "advanced debate": "Tranh biện chuyên sâu",
  "complex negotiation": "Đàm phán phức tạp",
  "rhetoric and style": "Tu từ và phong cách",
  "subtext and implication": "Ẩn ý và hàm ý",
  "rapid authentic speech": "Ngôn ngữ tự nhiên tốc độ cao",
  "regional and register variation awareness": "Nhận biết biến thể vùng miền và phong cách",
  "cultural references": "Tham chiếu văn hóa",
  "institutional communication": "Giao tiếp thể chế",
  "research presentation": "Trình bày nghiên cứu",
  "technical briefing": "Báo cáo kỹ thuật",
  "crisis communication": "Giao tiếp khủng hoảng",
  "leadership communication": "Giao tiếp lãnh đạo",
  "advanced media analysis": "Phân tích truyền thông nâng cao",
  "public policy": "Chính sách công",
  "economics and society": "Kinh tế và xã hội",
  "science and humanities": "Khoa học và nhân văn",
  "literature and arts": "Văn học và nghệ thuật",
  "intercultural mediation": "Điều phối liên văn hóa",
  "spontaneous expert response": "Phản hồi chuyên gia ứng biến",
  "advanced-stage integration III": "Tổng hợp cao cấp III"
};

/** Learner-facing Vietnamese label for an internal HSK authoring theme. */
export function hskThemeLabelVi(theme: string): string {
  return HSK_THEME_LABEL_VI[theme] ?? theme;
}

export function hasVietnameseHskThemeLabel(theme: string): boolean {
  return Object.prototype.hasOwnProperty.call(HSK_THEME_LABEL_VI, theme);
}
